# Site
name: "Divam Gupta"
description: "I work on AI for the real world. I’m currently at Meta Reality Labs and also the creator of Liner.ai."
meta_description: "I work on AI for the real world. I’m currently at Meta Reality Labs and also the creator of Liner.ai."
logo: 'assets/images/log.png'
favicon: 'assets/images/logo.png'
baseurl: ''
google_analytics: 'UA-140864507-1'
disqus: 'https-divamgupta-com'
mailchimp-list: 'https://divamgupta.us20.list-manage.com/subscribe/post?u=d7e18b84434b693a8d1cc9f26&id=038511d75f'

# Authors
authors:
  divam:
    name: Divam Gupta
    display_name: Divam Gupta
    gravatar: 9a823cb5c633fa70ef0c7b92e0d770df
    email: guptadivam@gmail.com
    web: https://divamgupta.com
    twitter: https://twitter.com/divamgupta
    description: "I’m a computer scientist passionate about working on AI for the real world. Currently, I am working towards achieving VR social telepresence at Meta Reality Labs. Before that, I did research at Carnegie Mellon University and Microsoft Research."


url: "https://divamgupta.com"

# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-archives
  - jekyll-sitemap
  - jekyll-seo-tag
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown
highlighter: rouge

