# Site
name: "Divam Gupta"
description: "I'm a graduate student at Carnegie Mellon University. I blog about Machine Learning and Deep Learning."
meta_description: "I'm a graduate student at Carnegie Mellon University. I blog about Machine Learning and Deep Learning."
logo: 'assets/images/log.png'
favicon: 'assets/images/logo.png'
baseurl: ''
google_analytics: 'UA-140864507-1'
disqus: 'https-divamgupta-com'
mailchimp-list: 'https://divamgupta.us20.list-manage.com/subscribe/post?u=d7e18b84434b693a8d1cc9f26&id=038511d75f'

# Authors
authors:
  divam:
    name: Divam Gupta
    display_name: Divam Gupta
    gravatar: 9a823cb5c633fa70ef0c7b92e0d770df
    email: guptadivam@gmail.com
    web: https://divamgupta.com
    twitter: https://twitter.com/divamgupta
    description: "I am currently a graduate student at the Robotics Institute, Carnegie Mellon University. Before that, I was a Research Fellow at Microsoft Research (MSR) India working on deep learning based unsupervised learning algorithms. My research interests lie broadly in applied machine learning, computer vision and natural language processing."


url: "https://divamgupta.com"

# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-archives
  - jekyll-sitemap
  - jekyll-seo-tag
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown
highlighter: rouge

