# Site
name: "Divam Gupta"
description: "Blog ..."
meta_description: "Blog ..."
logo: 'assets/images/log.png'
favicon: 'assets/images/logo.png'
baseurl: ''
google_analytics: 'UA-46278016-1'
disqus: 'demowebsite'
mailchimp-list: ''

# Authors
authors:
  divam:
    name: Divam Gupta
    display_name: Divam Gupta
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: guptadivam@gmail.com
    web: https://www.divamgupta.com
    twitter: https://twitter.com/divamgupta
    description: "I am a Research Fellow Microsoft Research (MSR) India working on deep learning based unsupervised learning algorithms. My research interests lie broadly in applied machine learning, computer vision and natural language processing."

# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown
highlighter: rouge

