# Site
name: "Divam Gupta"
description: "Blog ..."
meta_description: "Blog ..."
logo: 'assets/images/log.png'
favicon: 'assets/images/logo.png'
baseurl: ''
google_analytics: 'UA-140864507-1'
disqus: 'https-divamgupta-com'
mailchimp-list: ''

# Authors
authors:
  divam:
    name: Divam Gupta
    display_name: Divam Gupta
    gravatar: 9a823cb5c633fa70ef0c7b92e0d770df
    email: guptadivam@gmail.com
    web: https://divamgupta.com
    twitter: https://twitter.com/divamgupta
    description: "I am a Research Fellow at Microsoft Research (MSR) working on deep learning based unsupervised learning algorithms. My research interests lie broadly in applied machine learning, computer vision and natural language processing."

# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown
highlighter: rouge

